name: Production CI/CD Golang

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: kreasinusantara

jobs:
  build_and_push:
    runs-on: ubuntu-22.04
    name: Build image and push to registry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v1

  deploy:
    runs-on: ubuntu-22.04
    name: Deploy to EC2
    needs: build_and_push
    steps:
      - name: Connect and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        env:
          CONTAINER_NAME: kreasinusantara
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
          CONTAINER_PORT: ${{ secrets.CONTAINER_PORT }}
          ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          envs: CONTAINER_NAME,DOCKERHUB_USERNAME,HOST_PORT,CONTAINER_PORT,ENV_FILE,IMAGE_NAME
          script_stop: true
          script: |
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
            docker image rm $DOCKERHUB_USERNAME/$IMAGE_NAME:v1
            docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:v1
            docker run -dp $HOST_PORT:$CONTAINER_PORT \
            --name=$CONTAINER_NAME \
            --env-file=$ENV_FILE \
            $DOCKERHUB_USERNAME/$IMAGE_NAME:v1
            exit